baseurl = "http://amalog.net/"
languageCode = "ja"
title = "amalog.net"
author = "amane"
theme = "hugo-nagi"
description = "タフでグローバルになりたい"

[params]
  logo = "/images/profile.jpg"
  twitter = "https://twitter.com/sakueji"
  facebook = "https://www.facebook.com/amane.suzu"
  github = "https://github.com/amaotone"
  copyright = "2016 amalog.net all rights reserved."
